### ISSUE TITLE
로그인 후 API 요청시 403 에러 발생

### ISSUE THREAD

**Issue by Denia-park** [dkstm95/spring-boot-3-jwt-template#1]
안녕하세요. 승일님!

개발바닥 오픈 카톡방에서 승일님이 올려주신 프로젝트를 보고, 혼자서 스터디를 진행하다가 `로그인 관련 이슈`를 발견해서 제보드립니다!

# 이슈 상황
1. 회원 가입 -> 로그인 -> `/api/v1/auth` 가 아닌 주소 (`/api/v1/test/hello`)로 요청을 보내면 `403 에러`가 발생
(저는 제가 직접 `TestController.java`를 따로 만들어서, 테스트를 진행 했습니다.)

```java
// TestController.java
package com.seungilahn.springboot3jwttemplate.test;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RequestMapping("/api/v1/test")
@RestController
public class TestController {
        @RequestMapping("/hello")
        public String hello() {
            return "Hello World!";
        }
}

```

# 403 에러 발생 원인 파악
1. 기존에 승일님이 참고하신 소스랑 승일님 소스 모두 확인을 해보니 로그인시에 다른 점이 있던데 해당 부분 때문에 이슈가 발생한 것 같습니다.
    -  두 소스 모두 회원 가입시에 `accessToken`을 DB에 저장을 하도록 하는 것은 동일하나, 로그인시에 로직이 조금 달랐습니다.
        -  승일님 소스에서는 로그인시에 `refreshToken`을 DB에 다시 저장 하시는 것을 확인했습니다.
3. `Controller`로 요청을 보내기 전 Token을 검사하는 부분인 `JwtAuthenticationFilter.java` 파일에서 403 에러가 발생하는 이유를 찾았습니다. 
    - 해당 소스를 보면 `request`에서 `Authorization` Header를 찾고, `accessToken` 을 찾아옵니다.
    - 그리고 나서 `accessToken` 을 이용해서 `isValidToken` 변수 값을 구합니다. (※ 여기서 문제가 발생한 것 같습니다.)
    -  승일님 소스 대로라면 로그인시에 `refreshToken`을 DB에 저장을 하게 되는데, `accessToken`으로 DB를 조회하니 값을 찾을 수 없어서 `isValidToken`이 `false`가 되고 `SecurityContextHolder.getContext().setAuthentication(authToken)` 가 실행이 되지 않습니다.
4. 추가적인 테스트로 회원 가입 후 바로 `/api/v1/test/hello`로 요청을 보내면 정상적으로 응답을 합니다.
    - 회원가입시에는 `accessToken`으로 DB에 저장을 했기 때문에 `accessToken`로 DB 조회를 해도 정상적으로 조회가 됩니다.

```java
//JwtAuthenticationFilter.java
        String authHeader = request.getHeader("Authorization");
        if (authHeader == null || !authHeader.startsWith("Bearer ")) {
            filterChain.doFilter(request, response);
            return;
        }

        String jwt = authHeader.substring(7);
        String userEmail = jwtService.extractUsername(jwt);
        if (userEmail != null && SecurityContextHolder.getContext().getAuthentication() == null) {
            UserDetails userDetails = userDetailsService.loadUserByUsername(userEmail);
            boolean isValidToken = tokenRepository.findByToken(jwt)
                    .map(Token::isValid)
                    .orElse(false);
            if (jwtService.isTokenValid(jwt, userDetails) && isValidToken) {
                UsernamePasswordAuthenticationToken authToken = new UsernamePasswordAuthenticationToken(
                        userDetails,
                        null,
                        userDetails.getAuthorities()
                );
                authToken.setDetails(
                        new WebAuthenticationDetailsSource().buildDetails(request)
                );
                SecurityContextHolder.getContext().setAuthentication(authToken);
            }
        }
```

#### 참고한 소스 버전
- 승일님이 클린 아키텍처로 리팩터링 하시기 전의 소스를 참고했습니다. (`fix: move configuration files` 커밋 기준)

### 사용한 http-test.http 파일
```text
### Register User
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test1234@test.com",
  "password": "password",
  "name": "tester",
  "phone_number": "123456789",
  "role": "USER"
}

> {%
    client.global.set("auth-token", response.body.access_token);
    client.global.set("refresh-token", response.body.refresh_token);
    client.log("access_token : " + response.body.access_token);
    client.log("refresh_token : " + response.body.refresh_token);
%}

### login User
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "email": "test1234@test.com",
  "password": "password"
}

> {%
    client.global.set("auth-token", response.body.access_token);
    client.global.set("refresh-token", response.body.refresh_token);
    client.log("access_token : " + response.body.access_token);
    client.log("refresh_token : " + response.body.refresh_token);
%}

### test controller
GET http://localhost:8080/api/v1/test/hello
Authorization: Bearer {{auth-token}}

```

**Comment by Denia-park** [comment]
혹시 제가 잘못 테스트 했거나, 실수한게 있다면 말씀해주시면 감사하겠습니다.

**Comment by dkstm95** [comment]
안녕하세요, 형기님!

우선 이렇게 관심 가져주시고 이슈까지 올려주셔서 정말 감사드립니다 🙇 

말씀주신 부분들에 이슈가 있는 것은 확인했습니다, 이래서 테스트 코드는 정말 중요하네요 :(

개인적인 생각으로는 지역 변수 `isValidToken`를 선언 및 초기화하는 부분을 제거해도 괜찮지 않을까 하는 생각이 드는데요,
형기님은 어떻게 생각하시는지 궁금합니다.

**Comment by Denia-park** [comment]
@dkstm95 

> 개인적인 생각으로는 지역 변수 `isValidToken`를 선언 및 초기화하는 부분을 제거해도 괜찮지 않을까 하는 생각이 드는데요, 형기님은 어떻게 생각하시는지 궁금합니다.

사실 저도 해당 이슈로 트러블 슈팅 하면서 승일님 의견처럼 그냥  `isValidToken`를 제거해도 되지 않을까? 라는 생각을 많이 했습니다.

매 요청마다 DB에 접속해서 해당 토큰을 조회하는 것은 어찌보면 `JWT`를 쓰고 있지만 그냥 `Session`처럼 쓰고 있다는 느낌을 강하게 받아서 이럴꺼면 `Session`을 쓰는게 더 낫지 않을까? 라는 생각이 들었습니다.😅

**Comment by dkstm95** [comment]
형기님 말씀에 모두 동의합니다 :)

(형기님만 괜찮으시다면) 이슈 올려주신 김에 PR까지 진행해보면 어떨까 싶은데요 😃 

간단한 수정이라 제가 후딱 고쳐도 괜찮고, 편하게 의견주시면 감사하겠습니다 🙇

**Comment by Denia-park** [comment]
처음에 PR로 올려드릴까 고민을 했었는데 혹시라도 기분이 나쁘실수도 있겠다 라는 생각이 들어서 Issue로 올렸습니다.😅

승일님께서 먼저 PR 이야기를 해주셔서 해당 내용 반영하여 PR로 올렸습니다!!

**Comment by Denia-park** [comment]
PR 올리면서 코드를 추가적으로 살펴보다보니, 어제는 미처 발견하지 못한 부분을 발견했습니다.

`LogoutHandler` 구현체의 `logout` 메서드를 보시면 `accessToken`으로 DB에 저장된 Token을 찾고 revoke 시키는 로직이 있던데 이 부분도 수정이 필요해보입니다. 

(※ 로그아웃시에 `accessToken` 이 아니라 `refreshToken`을 보내는 로직을 예상하신거면 제가 착각한 것 같습니다!)

```java
        String jwt = authHeader.substring(7);
        Token storedToken = loadTokenPort.loadToken(jwt);
        if (storedToken != null) {
            storedToken.revoke();
            saveTokenPort.saveToken(storedToken);
            SecurityContextHolder.clearContext();
        }
```

**Comment by dkstm95** [comment]
아래 블로그 내용을 보면 로그아웃 API에서 `refreshToken`을 받도록 하면 될 것 같습니다.
[https://engineerinsight.tistory.com/232](url)

위 내용은 `README.md`만 수정해주면 될 것 같은데요,
`refreshToken`을 통해 새로운 `accessToken`을 발급받는 로직은 수정되어야 할 부분이 있는 것 같네요.

`RefreshTokenUseCase #tokenRefresh()` 메서드의 `refreshToken` 검증 로직 중 `Token` 클래스의 `revoked`와 `expired` 필드의 데이터가 `true`인지 확인하는 로직이 추가되어야 할 것 같습니다.

결국 방금 merge 되었던 `isValid()` 메서드가 필요하겠네요 😅 

이 내용은 별도의 이슈와 PR로 진행되면 좋을 것 같은데요, 괜찮으실까요?

**Comment by Denia-park** [comment]
> 아래 블로그 내용을 보면 로그아웃 API에서 `refreshToken`을 받도록 하면 될 것 같습니다. [https://engineerinsight.tistory.com/232](url)
> 
> 위 내용은 `README.md`만 수정해주면 될 것 같은데요,
> `refreshToken`을 통해 새로운 `accessToken`을 발급받는 로직은 수정되어야 할 부분이 있는 것 같네요.
> 
> `RefreshTokenUseCase #tokenRefresh()` 메서드의 `refreshToken` 검증 로직 중 `Token` 클래스의 `revoked`와 `expired` 필드의 데이터가 `true`인지 확인하는 로직이 추가되어야 할 것 같습니다.
> 
> 결국 방금 merge 되었던 `isValid()` 메서드가 필요하겠네요 😅

두 의견 모두 좋은 것 같습니다.😊

> 이 내용은 별도의 이슈와 PR로 진행되면 좋을 것 같은데요, 괜찮으실까요?

넵, 별도의 이슈로 처리하는 게 맞는 것 같습니다.👍👍👍

**Comment by dkstm95** [comment]
그럼 이 이슈는 닫겠습니다! 🙇
